USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ROUTEPULSE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute warehouse for RoutePulse analytics';

CREATE DATABASE IF NOT EXISTS ROUTEPULSE;

CREATE SCHEMA IF NOT EXISTS ROUTEPULSE.RAW;
CREATE SCHEMA IF NOT EXISTS ROUTEPULSE.ANALYTICS;

CREATE FILE FORMAT IF NOT EXISTS ROUTEPULSE.RAW.PARQUET_FORMAT
    TYPE = PARQUET;

USE WAREHOUSE ROUTEPULSE_WH;
USE DATABASE ROUTEPULSE;
USE SCHEMA RAW;
