USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ROUTEPULSE_WH;
USE DATABASE ROUTEPULSE;
USE SCHEMA RAW;

CREATE STAGE IF NOT EXISTS ROUTEPULSE_S3_STAGE
    URL = 's3://routepulse-raw-eu-central-1-9b355f4a/processed/realtime/'
    STORAGE_INTEGRATION = ROUTEPULSE_S3_INTEGRATION
    FILE_FORMAT = PARQUET_FORMAT
    COMMENT = 'External stage for RoutePulse processed Parquet datasets';

LIST @ROUTEPULSE_S3_STAGE
    PATTERN = '.*[.]parquet';
