USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ROUTEPULSE_WH;
USE DATABASE ROUTEPULSE;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS GTFS_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE OR REPLACE TRANSIENT TABLE GTFS_STOPS (
    STOP_ID VARCHAR,
    STOP_CODE VARCHAR,
    STOP_NAME VARCHAR,
    STOP_DESC VARCHAR,
    STOP_LAT FLOAT,
    STOP_LON FLOAT,
    LOCATION_TYPE INTEGER,
    PARENT_STATION VARCHAR,
    WHEELCHAIR_BOARDING INTEGER,
    PLATFORM_CODE VARCHAR,
    ZONE_ID VARCHAR,
    LEVEL_ID VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE GTFS_ROUTES (
    ROUTE_ID VARCHAR,
    AGENCY_ID VARCHAR,
    ROUTE_SHORT_NAME VARCHAR,
    ROUTE_LONG_NAME VARCHAR,
    ROUTE_TYPE INTEGER,
    ROUTE_COLOR VARCHAR,
    ROUTE_TEXT_COLOR VARCHAR,
    ROUTE_DESC VARCHAR
);

SELECT
    COUNT(*) AS stop_rows,
    COUNT(DISTINCT stop_id) AS distinct_stop_ids,
    COUNT_IF(stop_name IS NULL) AS missing_stop_names
FROM ROUTEPULSE.RAW.GTFS_STOPS;

SELECT
    COUNT(*) AS route_rows,
    COUNT(DISTINCT route_id) AS distinct_route_ids,
    COUNT_IF(
        route_short_name IS NULL
        AND route_long_name IS NULL
    ) AS routes_without_names
FROM ROUTEPULSE.RAW.GTFS_ROUTES;

SELECT
    stop_id,
    stop_name,
    stop_desc,
    platform_code
FROM ROUTEPULSE.RAW.GTFS_STOPS
LIMIT 10;

SELECT
    route_id,
    route_short_name,
    route_long_name,
    route_type
FROM ROUTEPULSE.RAW.GTFS_ROUTES
LIMIT 10;
