-- RoutePulse public Streamlit Community Cloud access.
--
-- Replace PASTE_PUBLIC_KEY_WITHOUT_HEADERS_OR_LINE_BREAKS with the public-key
-- body generated for the deployment. Never put the private key in SQL or Git.
--
-- This service identity is intentionally separate from ROUTEPULSE_APP_OWNER.
-- It can read the dashboard data and use one small warehouse, but it cannot
-- create, modify or delete RoutePulse data or Snowflake objects.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROUTEPULSE_PUBLIC_READER;

CREATE WAREHOUSE IF NOT EXISTS ROUTEPULSE_PUBLIC_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Read-only warehouse for the public RoutePulse portfolio app';

GRANT USAGE ON WAREHOUSE ROUTEPULSE_PUBLIC_WH
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT USAGE ON DATABASE ROUTEPULSE
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT USAGE ON SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT USAGE ON SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT SELECT ON TABLE ROUTEPULSE.RAW.GTFS_ROUTES
    TO ROLE ROUTEPULSE_PUBLIC_READER;

-- Presentation models are recreated during development. Future grants keep
-- the read-only public role working without broad write privileges.
GRANT SELECT ON FUTURE TABLES IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_PUBLIC_READER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_PUBLIC_READER;

CREATE USER IF NOT EXISTS ROUTEPULSE_PUBLIC_SERVICE
    TYPE = SERVICE
    DEFAULT_ROLE = ROUTEPULSE_PUBLIC_READER
    DEFAULT_WAREHOUSE = ROUTEPULSE_PUBLIC_WH
    RSA_PUBLIC_KEY = 'PASTE_PUBLIC_KEY_WITHOUT_HEADERS_OR_LINE_BREAKS'
    COMMENT = 'Read-only service user for the public RoutePulse Streamlit app';

-- Keep reruns and future key rotations deterministic if the user exists.
ALTER USER ROUTEPULSE_PUBLIC_SERVICE SET
    TYPE = SERVICE
    DEFAULT_ROLE = ROUTEPULSE_PUBLIC_READER
    DEFAULT_WAREHOUSE = ROUTEPULSE_PUBLIC_WH
    RSA_PUBLIC_KEY = 'PASTE_PUBLIC_KEY_WITHOUT_HEADERS_OR_LINE_BREAKS';

GRANT ROLE ROUTEPULSE_PUBLIC_READER
    TO USER ROUTEPULSE_PUBLIC_SERVICE;

-- Verification: both queries should return only the intended read-only role.
SHOW GRANTS TO USER ROUTEPULSE_PUBLIC_SERVICE;
SHOW GRANTS TO ROLE ROUTEPULSE_PUBLIC_READER;

-- Record these values in protected deployment secrets, not in Git.
SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME();
