-- RoutePulse access roles for the Snowflake-hosted Streamlit application.
-- Replace <DEPLOYER_USER> with the Snowflake user that deploys and tests the
-- native application. This is separate from Community Cloud stage 13.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROUTEPULSE_APP_OWNER;
CREATE ROLE IF NOT EXISTS ROUTEPULSE_VIEWER;

-- Allow the deployer to deploy and test using these roles.
GRANT ROLE ROUTEPULSE_APP_OWNER TO USER <DEPLOYER_USER>;
GRANT ROLE ROUTEPULSE_VIEWER TO USER <DEPLOYER_USER>;

-- Allow creation and execution of the Streamlit app.
GRANT USAGE ON DATABASE ROUTEPULSE
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT USAGE ON SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT CREATE STREAMLIT ON SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT USAGE ON WAREHOUSE ROUTEPULSE_WH
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU
    TO ROLE ROUTEPULSE_APP_OWNER;

-- Read-only access to the tables used by the app.
GRANT SELECT ON ALL TABLES IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT USAGE ON SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON ALL TABLES IN SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_APP_OWNER;

-- Keep access working if analytical or raw objects are recreated later.
GRANT SELECT ON FUTURE TABLES IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_APP_OWNER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA ROUTEPULSE.RAW
    TO ROLE ROUTEPULSE_APP_OWNER;

-- The viewer can locate the deployed app but receives no direct table access.
GRANT USAGE ON DATABASE ROUTEPULSE
    TO ROLE ROUTEPULSE_VIEWER;

GRANT USAGE ON SCHEMA ROUTEPULSE.ANALYTICS
    TO ROLE ROUTEPULSE_VIEWER;

-- Verification: confirm the owner role exists and inspect the deployer's
-- assigned roles after replacing the placeholder above.
SHOW ROLES LIKE 'ROUTEPULSE_APP_OWNER';
SHOW GRANTS TO USER <DEPLOYER_USER>;
